sequenceDiagram
actor User
User ->> PartyPopupController : createParty
activate PartyPopupController
PartyPopupController ->> PartyViewModel : createParty
activate PartyViewModel
PartyViewModel ->> User : getParties
activate User
User -->> PartyViewModel : #32; 
deactivate User
PartyViewModel ->> User : setParties
activate User
User -->> PartyViewModel : #32; 
deactivate User
PartyViewModel ->> User : getParties
activate User
User -->> PartyViewModel : #32; 
deactivate User
PartyViewModel ->> FirebaseUserRepository : updateUser
activate FirebaseUserRepository
FirebaseUserRepository ->> User : getId
activate User
User ->> FirebaseUserRepository : () -&gt;
activate FirebaseUserRepository
FirebaseUserRepository -->> User : #32; 
deactivate FirebaseUserRepository
User -->> FirebaseUserRepository : #32; 
deactivate User
FirebaseUserRepository ->> User : User::getId
activate User
User -->> FirebaseUserRepository : #32; 
deactivate User
FirebaseUserRepository -->> PartyViewModel : #32; 
deactivate FirebaseUserRepository
PartyViewModel ->> PartyBuilder : Runnable::run
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : id
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : name
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : type
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : members
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : bosses
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : quests
activate PartyBuilder
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> PartyBuilder : build
activate PartyBuilder
PartyBuilder ->> Party : new
activate Party
Party -->> PartyBuilder : #32; 
deactivate Party
PartyBuilder -->> PartyViewModel : #32; 
deactivate PartyBuilder
PartyViewModel ->> FirebasePartyRepository : setParty
activate FirebasePartyRepository
FirebasePartyRepository ->> Party : getId
activate Party
Party ->> FirebasePartyRepository : () -&gt;
activate FirebasePartyRepository
FirebasePartyRepository -->> Party : #32; 
deactivate FirebasePartyRepository
Party -->> FirebasePartyRepository : #32; 
deactivate Party
FirebasePartyRepository -->> PartyViewModel : #32; 
deactivate FirebasePartyRepository
PartyViewModel -->> PartyPopupController : #32; 
deactivate PartyViewModel
deactivate PartyPopupController
